[package]
name = "chatapp-db"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
sea-orm.workspace = true
sea-orm-migration.workspace = true
time.workspace = true
uuid.workspace = true

[lints]
workspace = true
